### ISSUE TITLE
Change vectors to lists (or forward lists) when applicable

### ISSUE THREAD

**Issue by Homailot** [DoStini/FEUP-AEDA-proj#28]
Options and Option Descriptions could be implemented as lists (linked-lists) instead of vectors.

**Comment by DoStini** [comment]
Nem terminaste isto... Enfim, devias ter 10

**Comment by Homailot** [comment]
Oh my God u are such a bitch baby

A quarta, 17/02/2021, 18:47, André Moreira <notifications@github.com>
escreveu:
